<#
.SYNOPSIS
    輪詢 GitHub，驅動 HERMES ↔ Claude 控制頻道（見同目錄 README.md）。
.DESCRIPTION
    兩件事,每次執行都做:
      1. 檢查 master 有沒有新 commit -- 有就呼叫 Invoke-HermesControlAction
         （目前只是個等你填內容的空殼)。
      2. 檢查控制 PR 有沒有 Claude 貼的新留言（用官方簽名
         "Generated by [Claude Code]" 辨識，排除 HERMES 自己貼的、避免自
         己回自己造成迴圈）-- 有就一樣丟給 Invoke-HermesControlAction。

    游標（上次處理到哪個 commit SHA / 哪個留言）存在同目錄的
    control_channel_cursor.json，第一次執行會用「當下的 HEAD / 當下最新
    留言」初始化，不會把 repo 的整段歷史都當成新事件處理一遍。

    跟 collect.ps1 共用同一個 .env（同目錄），需要三個新欄位：
    GITHUB_PAT / GITHUB_REPO / CONTROL_PR_NUMBER，見 README.md 的設定步驟。
.NOTES
    這支腳本只碰 GitHub API（github.com），不碰 Aiportal 自己的
    api-server，跟 collect.ps1 是兩條獨立的管線。
#>

$ErrorActionPreference = "Stop"
$ScriptDir = $PSScriptRoot
$ServiceDir = Split-Path $ScriptDir -Parent   # services/hermes-status

$CursorPath = Join-Path $ScriptDir "control_channel_cursor.json"
$LogDir = Join-Path $ScriptDir "logs"
$ErrorLogPath = Join-Path $LogDir "control_channel_error.log"

function Write-ErrorLog {
    param([string]$Message)
    if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir -Force | Out-Null }
    $line = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') | $Message"
    Add-Content -Path $ErrorLogPath -Value $line -Encoding UTF8
}

# 跟 collect.ps1 同一個地雷、同一個解法：PowerShell 5.1 的 Invoke-RestMethod
# 對 string Body 預設用 Latin-1 編碼，中文字會被吃成 '?'。送出前先把非 ASCII
# 字元跳脫成標準 JSON \uXXXX，GitHub API 收到後會正確還原。
function ConvertTo-AsciiJson {
    param([Parameter(ValueFromPipeline)][string]$Text)
    process {
        [regex]::Replace($Text, '[^\x00-\x7F]', { param($m) ('\u{0:x4}' -f [int][char]$m.Value) })
    }
}

# ── Load .env（跟 collect.ps1 共用同一份，同目錄）──────────────────────
$EnvPath = Join-Path $ServiceDir ".env"
if (-not (Test-Path $EnvPath)) {
    Write-ErrorLog "No .env found at $EnvPath -- copy .env.example and fill in GITHUB_PAT / GITHUB_REPO / CONTROL_PR_NUMBER."
    exit 1
}
$EnvConfig = @{}
Get-Content $EnvPath | ForEach-Object {
    if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$') {
        $EnvConfig[$matches[1]] = $matches[2]
    }
}
$GithubPat = $EnvConfig["GITHUB_PAT"]
$GithubRepo = $EnvConfig["GITHUB_REPO"]
$ControlPrNumber = $EnvConfig["CONTROL_PR_NUMBER"]
if (-not $GithubPat -or -not $GithubRepo -or -not $ControlPrNumber) {
    Write-ErrorLog "GITHUB_PAT / GITHUB_REPO / CONTROL_PR_NUMBER missing from .env"
    exit 1
}

$GithubHeaders = @{
    "Authorization" = "Bearer $GithubPat"
    "Accept"        = "application/vnd.github+json"
    "User-Agent"    = "hermes-control-channel"
}

# ── 這裡是你要接實際動作的地方 ──────────────────────────────────────────
# $trigger.kind 是 "commit" 或 "comment"；$trigger.detail 是對應的
# commit SHA/message 或留言內文。現在只寫 log，不做任何事——把你要的動作
# 接進來，最後回傳字串當作要貼回控制 PR 的回覆內容（回傳 $null 或空字串
# 就不貼回覆）。
function Invoke-HermesControlAction {
    param($trigger)
    Write-ErrorLog "Invoke-HermesControlAction 收到訊號（$($trigger.kind)），目前是空殼，尚未接上實際動作：$($trigger.detail)"
    return $null
}

function Get-Cursor {
    if (Test-Path $CursorPath) {
        try { return (Get-Content $CursorPath -Raw | ConvertFrom-Json) } catch { }
    }
    return $null
}

function Save-Cursor($cursor) {
    ($cursor | ConvertTo-Json) | Set-Content -Path $CursorPath -Encoding UTF8
}

function Add-ControlComment {
    param([string]$Body)
    $payload = @{ body = $Body } | ConvertTo-Json
    $resp = Invoke-RestMethod `
        -Uri "https://api.github.com/repos/$GithubRepo/issues/$ControlPrNumber/comments" `
        -Method Post -Headers $GithubHeaders -Body ($payload | ConvertTo-AsciiJson)
    return $resp
}

try {
    $cursor = Get-Cursor
    $firstRun = $null -eq $cursor
    if ($firstRun) { $cursor = @{ lastCommitSha = $null; lastCommentId = 0 } }

    # ── 1. 新 commit？────────────────────────────────────────────────
    $latestCommit = Invoke-RestMethod `
        -Uri "https://api.github.com/repos/$GithubRepo/commits/master" `
        -Method Get -Headers $GithubHeaders

    if ($firstRun) {
        # 第一次執行：只記住目前 HEAD，不把過去的歷史當成新事件處理。
        $cursor.lastCommitSha = $latestCommit.sha
    } elseif ($latestCommit.sha -ne $cursor.lastCommitSha) {
        $msg = $latestCommit.commit.message
        $reply = Invoke-HermesControlAction -trigger @{ kind = "commit"; detail = "$($latestCommit.sha.Substring(0,7)): $msg" }
        if ($reply) { Add-ControlComment -Body "[HERMES] $reply" | Out-Null }
        $cursor.lastCommitSha = $latestCommit.sha
    }

    # ── 2. Claude 貼的新留言？───────────────────────────────────────────
    $comments = Invoke-RestMethod `
        -Uri "https://api.github.com/repos/$GithubRepo/issues/$ControlPrNumber/comments?per_page=100" `
        -Method Get -Headers $GithubHeaders

    if ($firstRun) {
        # 同樣只記住目前最新的留言 id，不回頭處理歷史留言。
        $maxId = ($comments | Select-Object -ExpandProperty id -ErrorAction SilentlyContinue | Measure-Object -Maximum).Maximum
        $cursor.lastCommentId = if ($maxId) { $maxId } else { 0 }
    } else {
        # 只看比游標新、而且帶 Claude Code 官方簽名的留言——HERMES 自己貼
        # 的（不含這個簽名）不會被當成新事件，避免自己回自己造成無窮迴圈。
        $newComments = $comments | Where-Object {
            $_.id -gt $cursor.lastCommentId -and $_.body -match 'Generated by \[Claude Code\]'
        } | Sort-Object id

        foreach ($comment in $newComments) {
            $reply = Invoke-HermesControlAction -trigger @{ kind = "comment"; detail = $comment.body }
            if ($reply) { Add-ControlComment -Body "[HERMES] $reply" | Out-Null }
        }

        $maxId = ($comments | Select-Object -ExpandProperty id -ErrorAction SilentlyContinue | Measure-Object -Maximum).Maximum
        if ($maxId -and $maxId -gt $cursor.lastCommentId) { $cursor.lastCommentId = $maxId }
    }

    Save-Cursor $cursor
} catch {
    Write-ErrorLog "Control channel poll failed: $_"
    exit 1
}
